/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-09-09 07:25:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tap.model.Menu;
import java.util.ArrayList;
import java.util.TreeMap;
import java.util.Set;
import java.util.Map;
import java.util.Map.Entry;
import com.tap.model.CartItem;

public final class AddCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("com.tap.model.CartItem");
    _jspx_imports_classes.add("java.util.TreeMap");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.Map.Entry");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.tap.model.Menu");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<title>AddCart page</title>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("	#cart_items{\n");
      out.write("		height:200px;\n");
      out.write("		width:100%;\n");
      out.write("		background-color:#9dd5ec;\n");
      out.write("		padding-bottom:0px;\n");
      out.write("		padding-top:70px;\n");
      out.write("		padding-left:0px;\n");
      out.write("	}\n");
      out.write("	#img_of_menu{\n");
      out.write("		margin-top:-945px;\n");
      out.write("		margin-left:1020px;\n");
      out.write("		height:255px;\n");
      out.write("		width:300px;\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("	img{\n");
      out.write("		border-radius: 20px;\n");
      out.write("	}\n");
      out.write("	#info{\n");
      out.write("		width:300px;\n");
      out.write("		height:27px;\n");
      out.write("		font-size:18px;\n");
      out.write("	}\n");
      out.write("	#delet{\n");
      out.write("		margin-left:925px;\n");
      out.write("		margin-top:-133px;\n");
      out.write("	}\n");
      out.write("	#upd{\n");
      out.write("		margin-right:0px;\n");
      out.write("		padding:880px;\n");
      out.write("		margin-top:-994px;\n");
      out.write("	}\n");
      out.write("	#dell{\n");
      out.write("		background-color:darkred;\n");
      out.write("		color:white;\n");
      out.write("		font-size:20px;\n");
      out.write("		cursor: pointer;\n");
      out.write("		border-radius: 10px;\n");
      out.write("	}\n");
      out.write("	#dell:hover{\n");
      out.write("		background-color:rgb(255, 24, 24);\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#updt{\n");
      out.write("		background-color:rgb(253, 28, 234);\n");
      out.write("		color:white;\n");
      out.write("		font-size:20px;\n");
      out.write("		cursor: pointer;\n");
      out.write("		border-radius: 10px;\n");
      out.write("	}\n");
      out.write("	#updt:hover{\n");
      out.write("		background-color:#0af521;\n");
      out.write("	}\n");
      out.write("	#a{\n");
      out.write("	margin-left:50px;\n");
      out.write("	padding-left:50px;\n");
      out.write("	}\n");
      out.write("	#add_more{\n");
      out.write("		background-color:rgb(230, 163, 9);\n");
      out.write("		color:white;\n");
      out.write("		font-size:20px;\n");
      out.write("		margin-left:110px;\n");
      out.write("		font-size:25px;\n");
      out.write("		cursor: pointer;\n");
      out.write("		border-radius: 15px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#add_more:hover{\n");
      out.write("		background-color:rgb(248, 237, 14);\n");
      out.write("	}\n");
      out.write("	#proced_to_checkout:hover{\n");
      out.write("		background-color:#0af521;\n");
      out.write("	}\n");
      out.write("	#proced_to_checkout{\n");
      out.write("		background-color:green;\n");
      out.write("		color:white;\n");
      out.write("		font-size:20px;\n");
      out.write("		margin-left:100px;\n");
      out.write("		font-size:25px;\n");
      out.write("		cursor: pointer;\n");
      out.write("		border-radius: 15px;\n");
      out.write("	}\n");
      out.write("	#qnty{\n");
      out.write("		height:20px;\n");
      out.write("		width:60px;\n");
      out.write("		font-size:21px;\n");
      out.write("		cursor: pointer;\n");
      out.write("	}\n");
      out.write("	input[type=\"number\"]{\n");
      out.write("    width:70px;\n");
      out.write("    height:25px;\n");
      out.write("    }\n");
      out.write("	 table {\n");
      out.write("        border-collapse: collapse;\n");
      out.write("        width: 50%;\n");
      out.write("        margin-left:20px ;\n");
      out.write("    }\n");
      out.write("    th, td {\n");
      out.write("        border: 1px solid black;\n");
      out.write("        padding: 8px;\n");
      out.write("        text-align: left;\n");
      out.write("    }\n");
      out.write("    td{\n");
      out.write("    	background-color: rgb(244, 221, 207);\n");
      out.write("    }\n");
      out.write("    th {\n");
      out.write("        background-color: rgb(248, 5, 199);\n");
      out.write("    }\n");
      out.write("    #Addcart_det{\n");
      out.write("		padding-top:30px;    \n");
      out.write("		padding-left:440px;    \n");
      out.write("    	height:150px;\n");
      out.write("    	width:830px;\n");
      out.write("    	background-color: #f83f07;\n");
      out.write("    }\n");
      out.write("    @keyframes highlight {\n");
      out.write("   		0% { color: #FFD700; } \n");
      out.write("    	50% { color: #FF6347; } \n");
      out.write("   		100% { color: #FFD700; } \n");
      out.write("	}\n");
      out.write("		#cart_details{\n");
      out.write("		margin-top:0px;\n");
      out.write("		}\n");
      out.write("		input[type=\"button\"] {\n");
      out.write("        padding: 10px 20px;\n");
      out.write("        font-size: 18px;\n");
      out.write("        background-color: #4CAF50;\n");
      out.write("        color: white;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        cursor: pointer;\n");
      out.write("    }\n");
      out.write("    input[type=\"button\"]:hover {\n");
      out.write("       background-color:#0af521;\n");
      out.write("    }\n");
      out.write("    #home_button{\n");
      out.write("    margin-left:1150px;\n");
      out.write("    }\n");
      out.write("    input[type=\"button\"] {\n");
      out.write("        padding: 10px 20px;\n");
      out.write("        font-size: 18px;\n");
      out.write("        background-color: #4CAF50;\n");
      out.write("        color: white;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        cursor: pointer;\n");
      out.write("    }\n");
      out.write("    input[type=\"button\"]:hover {\n");
      out.write("       background-color:#0af521;\n");
      out.write("    }\n");
      out.write("    #home_button{\n");
      out.write("    margin-left:1050px;\n");
      out.write("    }\n");
      out.write("    #logout{\n");
      out.write("   		background-color:rgba(215, 3, 3, 0.778);\n");
      out.write("      	font-size: 18px;\n");
      out.write("        color: white;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        cursor: pointer;\n");
      out.write("    }\n");
      out.write("    #log_out{\n");
      out.write("    	margin-left:1150px;\n");
      out.write("    	margin-top:-40px;\n");
      out.write("    }\n");
      out.write("    #plus{\n");
      out.write("    	background-color:rgba(9, 246, 13, 0.778);\n");
      out.write("    	cursor: pointer;\n");
      out.write("    }\n");
      out.write("    #minus{\n");
      out.write("    	background-color:rgba(9, 246, 13, 0.778);\n");
      out.write("    	cursor: pointer;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>	\n");
      out.write("	<div id=\"home_button\"><a href=\"CallinServlet2\"><input type=\"button\" value=\"Home\"></button></a></div>\n");
      out.write("	<div id=\"log_out\"><a href=\"CallinLogOutServlet1?msg=logout_success\"> <button  id = \"logout\" class=\"btn btn-danger\"  value=\"Logout\">Logout<img src=\"imgfolder/logout.png\" height=\"35px\" width=\"35px\" alt=\"Logout\"></img></button></a></div>\n");
      out.write("	<div id=\"cart_details\"> <h1 style=\"text-align:center; text-shadow: 2px 2px 4px #888;\">Available Cart Items are </h1></div>\n");
      out.write("	");
  Map<Integer, CartItem> cart  = (Map<Integer,CartItem>)session.getAttribute("cart"); 
      out.write('\n');
      out.write('	');
 session.setAttribute("cart", cart);
	Menu singleMenu = (Menu)session.getAttribute("singleMenu");
	
      out.write('\n');
      out.write('	');
   float totalPrice =0;
	Set<Entry<Integer, CartItem>> entrys =  cart.entrySet(); 
		for(Entry<Integer, CartItem> entry :entrys){
			totalPrice = totalPrice + entry.getValue().getPrice();
	
      out.write("	\n");
      out.write("	<div id=\"cart_items\">	\n");
      out.write("	<form action=\"UpdateServlet1\">\n");
      out.write("	<input type=\"hidden\" name=\"menuId_u\" value=\"");
      out.print( entry.getValue().getItemId());
      out.write("\"></input>\n");
      out.write("	<table>\n");
      out.write("	<tr>\n");
      out.write("		<th>Menu name</th>\n");
      out.write("		<th>Price</th>\n");
      out.write("		<th>Quantity</th>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("	<td>");
      out.print( entry.getValue().getName() );
      out.write("</td>\n");
      out.write("	<td>&#8377;");
      out.print( entry.getValue().getPrice() );
      out.write("</td>\n");
      out.write("	<td>\n");
      out.write("	<button id=\"minus\" type=\"button\" onclick=\"decrementQuantity(");
      out.print( entry.getValue().getItemId() );
      out.write(")\">-</button>\n");
      out.write("  	<input type=\"number\" name=\"quantity_cart\" id=\"qnty");
      out.print( entry.getValue().getItemId() );
      out.write("\" min=\"1\" value=\"");
      out.print( entry.getValue().getQuantity() );
      out.write("\">\n");
      out.write("  	<button id=\"plus\" type=\"button\" onclick=\"incrementQuantity(");
      out.print( entry.getValue().getItemId() );
      out.write(")\">+</button>\n");
      out.write("	</td>\n");
      out.write("	</tr>\n");
      out.write("	</table>\n");
      out.write("	<pre>  	    <div id=\"info\"> </input> ");
 session.setAttribute("update", "update"); 
      out.write("   <div id=\"upd\">    <input type=\"submit\" id=\"updt\" name=\"update_btn\" value=\"update\"></input> </div><div id=\"img_of_menu\"><img src=\"");
      out.print( entry.getValue().getImgPath() );
      out.write("\" height=\"150px\" width=\"200px\"></img></div></pre>	\n");
      out.write("	<br></form>\n");
      out.write("	<form action=\"CallingAddCardServlet1\">\n");
      out.write("	<input type=\"hidden\" name=\"menuId_d\" value=\"");
      out.print( entry.getValue().getItemId());
      out.write("\"></input>\n");
      out.write("	<pre>  ");
 session.setAttribute("delete", "delete");
      out.write(" <div id=\"delet\"><input type=\"submit\" id=\"dell\" value=\"delete\"></input></div> </pre>	\n");
      out.write("	<br></form>\n");
      out.write("	");
} 
      out.write('\n');
      out.write('	');
 session.setAttribute("totalPrice", totalPrice); 
      out.write("\n");
      out.write("	<div id=\"Addcart_det\">\n");
      out.write("	<a href=\"Menu.jsp?\"> <input type=\"button\" id=\"add_more\" value=\"Add More Iteams\"></input></a><br><br>\n");
      out.write("	<a href=\"CheckoutValidation.jsp\"><input type=\"button\" id=\"proced_to_checkout\" value=\"Proced to checkout\"></input></a>\n");
      out.write("</div>\n");
      out.write("  \n");
      out.write("<script>\n");
      out.write("  function incrementQuantity(menuId) {\n");
      out.write("    var quantityInput = document.getElementById('qnty' + menuId);\n");
      out.write("    var currentValue = parseInt(quantityInput.value);\n");
      out.write("    quantityInput.value = currentValue + 1;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  function decrementQuantity(menuId) {\n");
      out.write("    var quantityInput = document.getElementById('qnty' + menuId);\n");
      out.write("    var currentValue = parseInt(quantityInput.value);\n");
      out.write("    if (currentValue > 1) {\n");
      out.write("      quantityInput.value = currentValue - 1;\n");
      out.write("    }\n");
      out.write("  }\n");
      out.write("</script>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("<h1 style=\"text-align:center; font-size: 40px; font-weight: bold; animation: highlight 2s infinite alternate; text-shadow: 2px 2px 4px #888;\">Available Cart Items are </h1>\n");
      out.write("	< TreeMap<Menu,Integer> cartItems =  (TreeMap<Menu,Integer>)session.getAttribute(\"cartItems\");\n");
      out.write("	 	float price =0.0f;\n");
      out.write("	 	int quantity = 0;\n");
      out.write("	 	Integer quantityObj = (Integer)session.getAttribute(\"quantity\");\n");
      out.write("		if(quantityObj!=null){\n");
      out.write("			quantity =  quantityObj.intValue();\n");
      out.write("		}\n");
      out.write("		Float priceObj = (Float)session.getAttribute(\"price\");\n");
      out.write("		if(priceObj!=null){\n");
      out.write("			price = priceObj.floatValue();\n");
      out.write("		}\n");
      out.write("	 	  Set<Entry<Menu,Integer>> entrys =  cartItems.entrySet();\n");
      out.write("	 	for(Entry<Menu,Integer> e : entrys){\n");
      out.write("	 		session.setAttribute(\"quantity1\", e.getValue());\n");
      out.write("	%>\n");
      out.write("	<form action=\"UpdateServlet1\">\n");
      out.write("	< session.setAttribute(\"menuId\", e.getKey().getMenuId()); %>\n");
      out.write("	<pre><= e.getKey().getName() %> &#8377;<= e.getKey().getPrice()%> <label for=\"quantity\" >Quantity</label> <input type=\"number\" name=\"quantity\" ></input> <input type=\"submit\" value=\"update\"></input><input type=\"button\" value=\"delete\"></input></pre>\n");
      out.write("	<br></form>\n");
      out.write("	<}\n");
      out.write(" %>\n");
      out.write("	<a href=\"Menu.jsp?\"><input type=\"button\" value=\"Add More Iteams\"></input></a><br><br>\n");
      out.write("	<button onclick=\"openPopup()\">Add to Cart items</button>\n");
      out.write("	<input type=\"button\" value=\"Proced to checkout\"></input> -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
