/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-09-09 07:25:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map;
import com.tap.model.CartItem;

public final class CheckOut_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.tap.model.CartItem");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<title>CheckOut page</title>\n");
      out.write("<style>\n");
      out.write("#checkout_container {\n");
      out.write("		margin: 100px auto;\n");
      out.write("		padding: 30px;\n");
      out.write("		width: 500px;\n");
      out.write("		background-color: #f9f9f9;\n");
      out.write("		border-radius: 10px;\n");
      out.write("		box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);\n");
      out.write("	}\n");
      out.write("	#checkout{\n");
      out.write("		width: 100%;\n");
      out.write("		height:600px;\n");
      out.write("		padding: 30px;\n");
      out.write("		background-color: hsl(182, 78%, 66%);\n");
      out.write("		border-radius: 10px;\n");
      out.write("		box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);\n");
      out.write("	}\n");
      out.write("	input, select, option, button {\n");
      out.write("		padding: 10px;\n");
      out.write("		font-size: 20px;\n");
      out.write("		width: 100%;\n");
      out.write("		margin-bottom: 20px;\n");
      out.write("		border: 1px solid #ccc;\n");
      out.write("		border-radius: 5px;\n");
      out.write("	}\n");
      out.write("	lable{\n");
      out.write("		font-size:25px;\n");
      out.write("	}\n");
      out.write("	button {\n");
      out.write("		background-color: #4CAF50; /* Green */\n");
      out.write("		color: white;\n");
      out.write("		border: none;\n");
      out.write("		cursor: pointer;\n");
      out.write("	}\n");
      out.write("	button:hover {\n");
      out.write("		background-color:#0af521;\n");
      out.write("	}\n");
      out.write("	#address{\n");
      out.write("	font-size: 25px;\n");
      out.write("	}\n");
      out.write("	@keyframes highlight {\n");
      out.write("   			 0% { color: #FFD700; } \n");
      out.write("   			 50% { color: #FF6347; } \n");
      out.write("   			 100% { color: #FFD700; } \n");
      out.write("	}\n");
      out.write("	@keyframes highlight3 {\n");
      out.write("    	0% { color: #FF4500; } \n");
      out.write("    	50% { color: rgb(17, 253, 5); } \n");
      out.write("    	100% { color: rgb(5, 253, 253); } \n");
      out.write("	}\n");
      out.write("	input[type=\"button\"] {\n");
      out.write("        padding: 10px 20px;\n");
      out.write("        font-size: 18px;\n");
      out.write("        background-color: #4CAF50;\n");
      out.write("        color: white;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        cursor: pointer;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    input[type=\"button\"]:hover {\n");
      out.write("       background-color:#0af521;\n");
      out.write("    }\n");
      out.write("  	#home_button{\n");
      out.write("      margin-left:1000px;\n");
      out.write("      margin-right:170px;\n");
      out.write("    }\n");
      out.write("    #logout{\n");
      out.write("   	background-color:rgba(215, 3, 3, 0.778);\n");
      out.write("    }\n");
      out.write("    #home_logout{\n");
      out.write("    	\n");
      out.write("    }\n");
      out.write("    #log_out{\n");
      out.write("    	margin-left:1130px;\n");
      out.write("    	margin-right:50px;\n");
      out.write("    	margin-top:-69px;\n");
      out.write("    	height:0px;\n");
      out.write("    	padding:20x;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"home_logout\">\n");
      out.write("<div id=\"home_button\"><a href=\"CallinServlet2\"><input type=\"button\" style=\"height:50px; width:120px\" value=\"Home\"></button></a></div>\n");
      out.write("<div id=\"log_out\"><a href=\"CallinLogOutServlet1?msg=logout_success\"> <button style=\"height:50px; width:120px\"  id = \"logout\" class=\"btn btn-danger\"  value=\"Logout\">Logout<img src=\"imgfolder/logout.png\" height=\"35px\" width=\"35px\" alt=\"Logout\"></img></button></a>\n");
      out.write("</div>\n");
      out.write("<div>\n");
      out.write("<div id=\"checkout\">\n");
      out.write("<div id=\"checkout_container\">\n");
      out.write("	<div><h1 style=\"text-align:center; font-size: 27px; font-weight: bold; animation: highlight3 2s infinite alternate; text-shadow: 2px 2px 4px #888;\">Enter the Address and Select the Payment mode option and click on confirm </h1></div>\n");
      out.write("	<form action=\"CallingOrderDetails\">\n");
      out.write("		<table>\n");
      out.write("			<tr> \n");
      out.write("				<td><lable for=\"Address\">Address</lable></td>\n");
      out.write("				<td><textarea rows=\"3\" cols=\"20\" name=\"address\" id=\"address\"></textarea></td>	\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td><lable for=\"PaymentMode\">PaymentMode</lable></td>\n");
      out.write("				<td>\n");
      out.write("					<select name=\"PaymentMode\" id=\"PaymentMode\">\n");
      out.write("						<option value=\"Cash on Delivery\">Cash on Delivery</option>\n");
      out.write("						<option value=\"UPI\">UPI</option>\n");
      out.write("						<option value=\"Debit Card\">Debit Card</option>\n");
      out.write("						<option value=\"Credit Card\">Creadit Card</option>\n");
      out.write("					</select>\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td><button name=\"confirm\">Confirm</button></td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("	</form>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
