/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-09-09 07:23:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.tap.model.Menu;
import com.tap.model.Restaurant;
import java.lang.Integer;
import java.util.Map;
import com.tap.model.CartItem;

public final class Menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.tap.model.CartItem");
    _jspx_imports_classes.add("com.tap.model.Restaurant");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.lang.Integer");
    _jspx_imports_classes.add("com.tap.model.Menu");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<title>Menu page</title>\n");
      out.write("<style>\n");
      out.write("	.restaurant_info{\n");
      out.write("	padding-left:270px;\n");
      out.write("	padding-top:0px;\n");
      out.write("	background-color:white:\n");
      out.write("	border: 2px solid black;\n");
      out.write("	}\n");
      out.write("	.menu_info{\n");
      out.write("    height:180px;\n");
      out.write("    padding-left:10px;\n");
      out.write("	padding-top:20px;\n");
      out.write("	padding-bottom:20px;\n");
      out.write("	width:100px;\n");
      out.write("	margin:20px;\n");
      out.write("	}\n");
      out.write("	#menu{\n");
      out.write("		padding-bottom:40px;\n");
      out.write("		padding-top:40px;\n");
      out.write("		background-color:violet;\n");
      out.write("	}\n");
      out.write("	#add_menu{\n");
      out.write("	margin-left:910px;\n");
      out.write("	margin-top:-25px;\n");
      out.write("	padding:5px 40px;\n");
      out.write("	cursor: pointer;\n");
      out.write("	}\n");
      out.write("	#quantity{\n");
      out.write("	margin-left:670px;\n");
      out.write("	margin-top:-7px;\n");
      out.write("	}\n");
      out.write("    input[type=\"number\"]{\n");
      out.write("    width:70px;\n");
      out.write("    height:25px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    }\n");
      out.write("    img{\n");
      out.write("		border-radius: 5px;\n");
      out.write("	} \n");
      out.write("	@keyframes highlight {\n");
      out.write("   		0% { color: #FFD700; } \n");
      out.write("   		50% { color: #FF6347; } \n");
      out.write("   		100% { color: #FFD700; } \n");
      out.write("	}\n");
      out.write("	 @keyframes highlight3 {\n");
      out.write("    	0% { color: #FF4500; } \n");
      out.write("    	50% { color: rgb(17, 253, 5); } \n");
      out.write("    	100% { color: rgb(5, 253, 253); } \n");
      out.write("	}\n");
      out.write("	input[type=\"button\"] {\n");
      out.write("       padding: 10px 20px;\n");
      out.write("       font-size: 18px;\n");
      out.write("       background-color: #4CAF50;\n");
      out.write("       color: white;\n");
      out.write("       border: none;\n");
      out.write("       border-radius: 5px;\n");
      out.write("       cursor: pointer;\n");
      out.write("    }\n");
      out.write("    input[type=\"button\"]:hover {\n");
      out.write("       background-color:#0af521;\n");
      out.write("    }\n");
      out.write("    #home_button{\n");
      out.write("    margin-left:1050px;\n");
      out.write("    margin-top:20px;\n");
      out.write("    }\n");
      out.write("    #logout{\n");
      out.write("   	 background-color:rgba(215, 3, 3, 0.778);\n");
      out.write("     font-size: 18px;\n");
      out.write("     color: white;\n");
      out.write("     border: none;\n");
      out.write("     border-radius: 5px;\n");
      out.write("     cursor: pointer;\n");
      out.write("    }\n");
      out.write("    #log_out{\n");
      out.write("    	margin-left:1150px;\n");
      out.write("    	margin-top:-40px;\n");
      out.write("    }\n");
      out.write("    #plus{\n");
      out.write("    	background-color:rgba(9, 246, 13, 0.778);\n");
      out.write("    	cursor: pointer;\n");
      out.write("    }\n");
      out.write("    #minus{\n");
      out.write("    	background-color:rgba(9, 246, 13, 0.778);\n");
      out.write("    	cursor: pointer;\n");
      out.write("    }\n");
      out.write("    .menu_info{\n");
      out.write("    width:1100px;\n");
      out.write("    margin-left:85px;\n");
      out.write("    background-color:#9dd5ec;\n");
      out.write("    }\n");
      out.write("    span{\n");
      out.write("    	font-size:20px;\n");
      out.write("    }\n");
      out.write("    #menu_info_sub{\n");
      out.write("    	padding-right:300px;\n");
      out.write("    	padding-left:100px;\n");
      out.write("    }\n");
      out.write("    #image_div{\n");
      out.write("    	margin-left:900px;\n");
      out.write("    	margin-top:-70px;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write(" </head>\n");
      out.write("<body>\n");
      out.write("	<div id=\"home_button\"><a href=\"CallinServlet2\"><input type=\"button\" value=\"Home\"></button></a></div>\n");
      out.write("	<div id=\"log_out\"><a href=\"CallinLogOutServlet1?msg=logout_success\"> <button  id = \"logout\" class=\"btn btn-danger\"  value=\"Logout\">Logout<img src=\"imgfolder/logout.png\" height=\"35px\" width=\"35px\" alt=\"Logout\"></img></button></a></div>\n");
      out.write("	<div><h1 style=\"text-align:center;  text-shadow: 2px 2px 4px #888;\">Available menus in the Restaurants</h1></div>\n");
      out.write("	");
 Restaurant restaurant = (Restaurant)session.getAttribute("restaurant"); 
      out.write('\n');
      out.write('	');
      out.write('	');
 session.setAttribute("restaurantId", restaurant.getRestaurantId());
      out.write("\n");
      out.write("		<div  class =\"restaurant_info\">\n");
      out.write("			<div>\n");
      out.write("				<h1 style=\"font-size: 25px; \">");
      out.print( restaurant.getName() );
      out.write("</h1>\n");
      out.write("				<span><img src=\"https://th.bing.com/th/id/OIP.S3qinUY9mFxFcufBsjO1XAHaHa?rs=1&pid=ImgDetMain\" height=\"16px\"; width=\"16px\"> ");
      out.print( restaurant.getRating() );
      out.write(" </span><br>\n");
      out.write("    			<span style=\"color:orange;\">");
      out.print( restaurant.getCuisinType() );
      out.write("</span><br>\n");
      out.write("    			<span> ");
      out.print( restaurant.getAddress() );
      out.write("</span><br>\n");
      out.write("    			<span> ");
      out.print( restaurant.getEta() );
      out.write('-');
      out.print( restaurant.getEta()+5 );
      out.write(" mins</span><br>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	<div id=\"menu_Restaurant\">\n");
      out.write("	<div id=\"menu\">\n");
      out.write("		");
 List<Menu> menulist = (List<Menu>)session.getAttribute("allMenu");
		if(menulist != null){
		 for(Menu menu : menulist){
		
      out.write("\n");
      out.write("			<div class=\"menu_info\">\n");
      out.write("			<div class=\"menu_delails\">\n");
      out.write("				<div id=\"menu_info_sub\">\n");
      out.write("				<span style=\"font-size:20px;\">");
      out.print( menu.getName());
      out.write("</span><br>\n");
      out.write("				");
      out.print( "₹"+menu.getPrice());
      out.write("<br>\n");
      out.write("				");
      out.print( menu.getDescription());
      out.write("<br>\n");
      out.write("				</div>\n");
      out.write("				<div id=\"image_div\"><img src=\"");
      out.print( menu.getImagepath());
      out.write("\" class =\"menuimg\" alter=\"image not found\" height=\"130px\" width=\"130px\"></div>\n");
      out.write("			</div>\n");
      out.write("			<form action=\"CallingAddCardServlet1\">\n");
      out.write("			<input type=\"hidden\" name=\"menuId\" value=\"");
      out.print( menu.getMenuId() );
      out.write("\">\n");
      out.write("  <div id=\"quantity\">\n");
      out.write("  <label for=\"quantity_m\">Quantity</label>\n");
      out.write("  <button id=\"minus\" type=\"button\" onclick=\"decrementQuantity(");
      out.print( menu.getMenuId() );
      out.write(")\">-</button>\n");
      out.write("  <input type=\"number\" name=\"quantity_m\" id=\"quantity_m");
      out.print( menu.getMenuId() );
      out.write("\" value=\"0\">\n");
      out.write("  <button id=\"plus\" type=\"button\" onclick=\"incrementQuantity(");
      out.print( menu.getMenuId() );
      out.write(")\">+</button>\n");
      out.write("</div>\n");
      out.write("	<div id=\"Add_buttn\">\n");
      out.write("		");
 session.setAttribute("add","add"); 
      out.write("<button  id =\"add_menu\" >add</button>\n");
      out.write("		</div><br>\n");
      out.write("		</form>\n");
      out.write("		</div>\n");
      out.write("		");
 }} 
      out.write("		\n");
      out.write("	</div>\n");
      out.write("	<div>\n");
      out.write("	");
 Map<Integer, CartItem> cart = (Map<Integer, CartItem>)session.getAttribute("cart");
	Boolean  showConfirmation = (Boolean)request.getAttribute("showConfirmation");
	Integer prev_restaurantIdObj  = (Integer)session.getAttribute("prev_restaurantId");
	int prev_restaurantId = 0;
	if(prev_restaurantIdObj!=null){
		prev_restaurantId = prev_restaurantIdObj.intValue();
	}
	 if(prev_restaurantId != 0 && restaurant.getRestaurantId()!= prev_restaurantId && cart != null){ 
      out.write("\n");
      out.write("    <script>\n");
      out.write("        var resetCart = confirm(\"Your cart contains items from another restaurant. Would you like to reset your cart for adding items from this restaurant?\");\n");
      out.write("        if (resetCart) {\n");
      out.write("        	");
 if(cart!=null){
        		cart.clear();
        	}
      out.write("\n");
      out.write("            var menuId = document.getElementById('menuId').value; // Get the menuId from the hidden input field\n");
      out.write("       	    window.location.href = \"CallingAddCardServlet1?menuId=\" + menuId;\n");
      out.write("        } else {\n");
      out.write("            window.location.href = \"Menu.jsp\";\n");
      out.write("        }\n");
      out.write("   \n");
}else if(prev_restaurantId != 0){
      out.write("\n");
      out.write("	window.location.href = \"CallingAddCardServlet1\";\n");
}
      out.write("\n");
      out.write("</script>\n");
      out.write("	<script>\n");
      out.write("  function incrementQuantity(menuId) {\n");
      out.write("    var quantityInput = document.getElementById('quantity_m' + menuId);\n");
      out.write("    var currentValue = parseInt(quantityInput.value);\n");
      out.write("    quantityInput.value = currentValue + 1;\n");
      out.write("  }\n");
      out.write("  function decrementQuantity(menuId) {\n");
      out.write("    var quantityInput = document.getElementById('quantity_m' + menuId);\n");
      out.write("    var currentValue = parseInt(quantityInput.value);\n");
      out.write("    if (currentValue > 0) {\n");
      out.write("      quantityInput.value = currentValue - 1;\n");
      out.write("    }\n");
      out.write("  }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("<!-- \n");
      out.write("else {\n");
      out.write("        	<\n");
      out.write("        	cart.clear();\n");
      out.write("        	RequestDispatcher rd = request.getRequestDispatcher(\"CallingAddCardServlet1\");\n");
      out.write("    		rd.forward(request, response);%>\n");
      out.write("            // Handle \"No\" option - maybe continue with the current operation\n");
      out.write("        }\n");
      out.write(".menu_delails{\n");
      out.write("	margin-left:100px;\n");
      out.write("	margin-right:300px;\n");
      out.write("	margin-bottom:-50px;\n");
      out.write("	}\n");
      out.write("	.menuimg{\n");
      out.write("	padding-bottom:10px;\n");
      out.write("	padding-left:800px;\n");
      out.write("	margin-bottom:-80px;\n");
      out.write("	margin-top:-80px;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"quantity\"><label for=\"quantity\">Quantity</label>\n");
      out.write("				<input type=\"number\"   name=\"quantity_m\" min=\"1\"></input>\n");
      out.write("			</div> \n");
      out.write("			<h1 style=\"text-align:center; font-size: 50px; font-weight: bold; animation: highlight 2s infinite alternate; text-shadow: 2px 2px 4px #888;\">All menus in the below Restaurants</h1>\n");
      out.write("			-->\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
