/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-09-09 07:22:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tap.model.Restaurant;
import java.util.List;

public final class Restaurant1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.tap.model.Restaurant");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\n");
      out.write("<style>\n");
      out.write("    #wel_Section{\n");
      out.write("        height:200px;\n");
      out.write("        width:100%; \n");
      out.write("    }\n");
      out.write("    #unp{\n");
      out.write("        padding-top:50px;\n");
      out.write("        padding-left:470px;\n");
      out.write("        font-size:25px;\n");
      out.write("    }\n");
      out.write("    .restaurant{\n");
      out.write("        margin-left:18px;\n");
      out.write("        margin-right:0px;\n");
      out.write("        padding:10px;    \n");
      out.write("        float:left;\n");
      out.write("        background-color: white;\n");
      out.write("        box-sizing: border-box;\n");
      out.write("        \n");
      out.write("    }\n");
      out.write("    .restaurant1{\n");
      out.write("    	margin-left:18px;\n");
      out.write("        margin-right:0px;\n");
      out.write("        padding:10px;    \n");
      out.write("        background-color: white;\n");
      out.write("        border-radius: 20px;\n");
      out.write("        box-sizing: border-box;\n");
      out.write("    }\n");
      out.write("    img{\n");
      out.write("        border-radius:15px;\n");
      out.write("    }\n");
      out.write("    #restaurant_name{\n");
      out.write("        font-size:20px;\n");
      out.write("    }\n");
      out.write(" 	.restaurant:hover{\n");
      out.write("        transform :scale(0.95);\n");
      out.write("    }\n");
      out.write("    .restaurant1:hover{\n");
      out.write("    	transform :scale(0.95);\n");
      out.write("    }\n");
      out.write("    .first_line{\n");
      out.write("        display :flex;\n");
      out.write("        margin-left:450px;\n");
      out.write("        font-size:50px;\n");
      out.write("    }\n");
      out.write("    #wel_Tap{\n");
      out.write("        margin-left:450px;\n");
      out.write("        font-size:50px;\n");
      out.write("        animation-name:ani;\n");
      out.write("      	animation-duration:20s;\n");
      out.write("       	position:relative;\n");
      out.write("    }\n");
      out.write("    button{\n");
      out.write("        font-size:25px;\n");
      out.write("         margin-left:30px;\n");
      out.write("    }\n");
      out.write("    #name{\n");
      out.write("    font-size:25px;\n");
      out.write("    margin-left:300px;\n");
      out.write("    padding-left:20px;\n");
      out.write("    text-align:center;\n");
      out.write("    }\n");
      out.write("    #logout{\n");
      out.write("    	margin-left:200px;\n");
      out.write("    }\n");
      out.write("  	#prevBtn,#nextBtn\n");
      out.write("    {\n");
      out.write("    	border-radius: 30%;\n");
      out.write("    	\n");
      out.write("    }\n");
      out.write("     @keyframes ani {\n");
      out.write("            10%{background-color: red; left:50px;top:90px}\n");
      out.write("            20%{background-color: blueviolet;left:80px;right:20px}\n");
      out.write("            30%{background-color: green;bottom:40px;}\n");
      out.write("            100%{background-color: yellow;left:0}\n");
      out.write("            /* 30%{background-color:blue;}\n");
      out.write("            20%{background-color:chartreuse;} */\n");
      out.write("        }\n");
      out.write("        @keyframes highlight1 {\n");
      out.write("    		0% { color: #FF4500; } \n");
      out.write("    		50% { color: #4169E1; } \n");
      out.write("    		100% { color: #FF4500; } \n");
      out.write("		}\n");
      out.write("		@keyframes highlight3 {\n");
      out.write("    		0% { color: #FF4500; } \n");
      out.write("    		50% { color: rgb(253, 5, 212); } \n");
      out.write("    		100% { color: rgb(5, 253, 253); } \n");
      out.write("		}\n");
      out.write("        @keyframes highlight {\n");
      out.write("   			 0% { color: #FFD700; } \n");
      out.write("    		50% { color: #FF6347; } \n");
      out.write("   			 100% { color: #FFD700; } \n");
      out.write("		}\n");
      out.write("     #home_Buttons{\n");
      out.write("     	background-color:rgb(5, 253, 92);\n");
      out.write("     	height:180px;\n");
      out.write("     }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div>\n");
      out.write("<div id=\"home_Buttons\">\n");
      out.write("  <span id=\"wel_Tap\" style=\"text-align:center; font-size: 50px; font-weight: bold; animation: highlight 2s infinite alternate; text-shadow: 2px 2px 4px #888;\"> Welcome to TapFoods</span>\n");
      out.write("         <a href=\"CallinLogOutServlet1?msg=logout_success\"> <button  id = \"logout\" class=\"btn btn-danger\"  value=\"Logout\">Logout<img src=\"imgfolder/logout.png\" height=\"35px\" width=\"35px\" alt=\"Logout\"></img></button></a><br><br>\n");
      out.write("    <span id =\"name\" style=\"text-align:center; font-size: 25px; font-weight: bold; animation: highlight1 2s infinite alternate; text-shadow: 2px 2px 4px #888;\"> ");
      out.print( "Hello "+" "+session.getAttribute("userName")+" Welcome to TapFoods " );
      out.write("</span>\n");
      out.write("          <a href=\"ViewCart.jsp\"> <button type=\"button\" class=\"btn btn-info\">View Cart</button></a>\n");
      out.write("          <a href=\"CallingOrderHistory\"><button type=\"button\" class=\"btn btn-info\">View Order History</button></a>\n");
      out.write("   </div>\n");
      out.write("    <br>        \n");
      out.write("    <div><h1 style=\"text-align:center; font-size: 30px; font-weight: bold; animation: highlight3 2s infinite alternate; text-shadow: 2px 2px 4px #888;\">Top Restaurants in Bengaluru</h1></div>\n");
      out.write("  <button id=\"prevBtn\">&#9664;</button>\n");
      out.write("  <button id=\"nextBtn\">&#9654;</button>\n");
      out.write("  <div id=\"restaurantContainer\" style=\"overflow-x: auto; white-space: nowrap;\">\n");
 
    List<Restaurant> all_Top_Restaurant = (List<Restaurant>)request.getAttribute("all_Top_Restaurant"); 
    for(Restaurant restaurant : all_Top_Restaurant){

      out.write("\n");
      out.write("<div class = \"restaurant1\" style=\"display: inline-block\">\n");
      out.write("    <a href=\"MenuServlet?restaurantId=");
      out.print( restaurant.getRestaurantId() );
      out.write("\"><img src = \"");
      out.print( restaurant.getImagePath() );
      out.write("\" alter = \"image not found\" height=\"190px\" width=\"270px\" ></a> <br>\n");
      out.write("    <span id=\"restaurant_name\">");
      out.print( restaurant.getName() );
      out.write("</span><br>\n");
      out.write("    <span><img src=\"https://th.bing.com/th/id/OIP.S3qinUY9mFxFcufBsjO1XAHaHa?rs=1&pid=ImgDetMain\" height=\"16px\"; width=\"16px\"> ");
      out.print( restaurant.getRating() );
      out.write(" .</span>\n");
      out.write("    <span>");
      out.print( restaurant.getEta() );
      out.write('-');
      out.print( restaurant.getEta()+5 );
      out.write("</span><br>\n");
      out.write("    <span>");
      out.print( restaurant.getCuisinType() );
      out.write("</span><br>\n");
      out.write("    <span>");
      out.print( restaurant.getAddress() );
      out.write("</span><br>\n");
      out.write("</div>\n");
 }
      out.write("\n");
      out.write("</div><br><br>\n");
      out.write("<div><h1 style=\"text-align:center; font-size: 30px; font-weight: bold; animation: highlight3 2s infinite alternate; text-shadow: 2px 2px 4px #888;\">All Restaurants in Bengaluru</h1></div>\n");
      out.write(" <div class = \"restaurant\" style=\"display: inline-block\">\n");
 
    List<Restaurant> restaurantlist = (List<Restaurant>)request.getAttribute("allRestaurant"); 
    for(Restaurant restaurant : restaurantlist){

      out.write("\n");
      out.write("<div class = \"restaurant\" style=\"display: inline-block\">\n");
      out.write("    <a href=\"MenuServlet?restaurantId=");
      out.print( restaurant.getRestaurantId() );
      out.write("\"><img src = \"");
      out.print( restaurant.getImagePath() );
      out.write("\" alter = \"image not found\" height=\"190px\" width=\"270px\" ></a> <br>\n");
      out.write("    <span id=\"restaurant_name\">");
      out.print( restaurant.getName() );
      out.write("</span><br>\n");
      out.write("    <span><img src=\"https://th.bing.com/th/id/OIP.S3qinUY9mFxFcufBsjO1XAHaHa?rs=1&pid=ImgDetMain\" height=\"16px\"; width=\"16px\"> ");
      out.print( restaurant.getRating() );
      out.write(" .</span>\n");
      out.write("    ");
 int max_time = restaurant.getEta();
    max_time = max_time + 5; 
    
      out.write("\n");
      out.write("    <span>");
      out.print( restaurant.getEta() +"-"+max_time );
      out.write("</span><br>\n");
      out.write("    <span>");
      out.print( restaurant.getCuisinType() );
      out.write("</span><br>\n");
      out.write("    <span>");
      out.print( restaurant.getAddress() );
      out.write("</span><br>\n");
      out.write("</div>\n");
 
    }

      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
 String login_msg = (String)session.getAttribute("login_success");
	if(login_msg != null && login_msg.equals("login_success")){ 
      out.write("\n");
      out.write("		<script> alert(\"Login Success\")</script>\n");
      out.write("		");
 login_msg = null; 
      out.write('\n');
} session.removeAttribute("login_success");
      out.write('\n');
      out.write('\n');
 String alertMessage_cart = (String)session.getAttribute("alert"); 
   if(alertMessage_cart!=null && alertMessage_cart.equals("Cart is Empty")){ 
      out.write("\n");
      out.write("   <script> alert(\"Cart is Empty\")</script>\n");
      out.write(" ");
} session.removeAttribute("alert");
      out.write("\n");
      out.write(" \n");
      out.write(" ");
 String alertMessage_history = (String)session.getAttribute("alert_history"); 
   if(alertMessage_history!=null && alertMessage_history.equals("no Order History Available")){ 
      out.write("\n");
      out.write("   <script> alert(\"Order History is not Available\")</script>\n");
      out.write(" ");
} session.removeAttribute("alert_history");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("    <script>\n");
      out.write("        const restaurantContainer = document.getElementById('restaurantContainer');\n");
      out.write("        const prevBtn = document.getElementById('prevBtn');\n");
      out.write("        const nextBtn = document.getElementById('nextBtn');\n");
      out.write("\n");
      out.write("        prevBtn.addEventListener('click', function() {\n");
      out.write("            restaurantContainer.scrollLeft -= 100; \n");
      out.write("        });\n");
      out.write("\n");
      out.write("        nextBtn.addEventListener('click', function() {\n");
      out.write("            restaurantContainer.scrollLeft += 100; \n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write(" \n");
      out.write(" </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("                <!-- \n");
      out.write("                <button type=\"button\" class=\"btn btn-primary\">Primary Button</button>\n");
      out.write("                <button type=\"button\" class=\"btn btn-danger\">Danger Button</button>\n");
      out.write("                <button type=\"button\" class=\"btn btn-success\">Success Button</button>\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\">Secondary Button</button>\n");
      out.write("                <button type=\"button\" class=\"btn btn-warning\">Warning Button</button>\n");
      out.write("                <button type=\"button\" class=\"btn btn-light\">Light Button</button>\n");
      out.write("                <button type=\"button\" class=\"btn btn-dark\">Dark Button</button>\n");
      out.write("                <button type=\"button\" class=\"btn btn-link\">Link Button</button> -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
