/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-09-09 07:23:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map;
import com.tap.model.CartItem;
import java.util.Set;
import java.util.Map.Entry;

public final class ViewCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.tap.model.CartItem");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.Map.Entry");
    _jspx_imports_classes.add("java.util.Set");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<title>View Cart from cart</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\n");
      out.write("<style>\n");
      out.write("	 table {\n");
      out.write("    border-collapse: collapse;\n");
      out.write("    width: 100%;\n");
      out.write("  }\n");
      out.write("  th, td {\n");
      out.write("    border: 1px solid #ddd; \n");
      out.write("    padding: 15px;\n");
      out.write("    text-align: left;\n");
      out.write("    font-size:25px;\n");
      out.write("  }\n");
      out.write("  td{\n");
      out.write("    background-color: #ebc4c0; \n");
      out.write("  \n");
      out.write("  }\n");
      out.write("  th {\n");
      out.write("    background-color: #fe07c5; \n");
      out.write("  }\n");
      out.write("  #totle1{\n");
      out.write("    text-align: center;\n");
      out.write("    background-color:#64e7de;\n");
      out.write("   }\n");
      out.write("  #totle2{\n");
      out.write("   background-color:#64e7de;\n");
      out.write("  }\n");
      out.write("	 #totle1{\n");
      out.write("	 	text-align:center;\n");
      out.write("	 	padding-left:50px;\n");
      out.write("	 }\n");
      out.write("	  #totle1, #totle2 {\n");
      out.write("        text-align: center;\n");
      out.write("        }\n");
      out.write("        @keyframes highlight3 {\n");
      out.write("    		0% { color: #FF4500; } \n");
      out.write("    		50% { color: rgb(17, 253, 5); } \n");
      out.write("    		100% { color: rgb(5, 253, 253); } \n");
      out.write("		}\n");
      out.write("	input[type=\"button\"] {\n");
      out.write("        padding: 10px 20px;\n");
      out.write("        font-size: 18px;\n");
      out.write("        background-color: #4CAF50;\n");
      out.write("        color: white;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        cursor: pointer;\n");
      out.write("    }\n");
      out.write("	div{\n");
      out.write("    float:right;\n");
      out.write("    display:flex;\n");
      out.write("    margin-left:5px;\n");
      out.write("    margin-bottom:50px;\n");
      out.write("    }\n");
      out.write("    #home_button{\n");
      out.write("    margin-left:0px;\n");
      out.write("    }\n");
      out.write("   h1{\n");
      out.write("        text-align: center;\n");
      out.write("        padding-top:30px;\n");
      out.write("        margin-left:200px;\n");
      out.write("        color:rgb(7, 3, 243);\n");
      out.write("    }\n");
      out.write("    h1:hover{\n");
      out.write("    	color:rgb(248, 5, 248);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div>\n");
      out.write("<div id=\"home_button\"><a href=\"CallinServlet2\"><input type=\"button\" value=\"Home\"></button></a></div>\n");
      out.write("<div><a href=\"CallinLogOutServlet1?msg=logout_success\"> <button  id = \"logout\" class=\"btn btn-danger\"  value=\"Logout\">Logout<img src=\"imgfolder/logout.png\" height=\"35px\" width=\"35px\" alt=\"Logout\"></img></button></a></div>\n");
      out.write("</div>\n");
      out.write("	");
  Map<Integer, CartItem> cart  = (Map<Integer,CartItem>)session.getAttribute("cart"); 
		Float  totalPriceFloat = (Float)session.getAttribute("totalPrice");
		float totalPrice = 0.0f;
		if(totalPriceFloat != null){
			totalPrice = totalPriceFloat.floatValue();
		}
		if(cart == null || cart.isEmpty()){ 
      out.write("\n");
      out.write("			");
 session.setAttribute("alert", "Cart is Empty") ;
      out.write('\n');
      out.write('	');
      out.write('	');
 RequestDispatcher rd = request.getRequestDispatcher("CallinServlet2");
		rd.forward(request, response);
		}
		else if(!cart.isEmpty()){
		
      out.write("\n");
      out.write("			<h1> See the View Cart Items</h1>\n");
      out.write("			<table>\n");
      out.write("			<tr>\n");
      out.write("			<th>ItemId </th>\n");
      out.write("			<th>RestaurantId</th>\n");
      out.write("			<th>itemName</th>\n");
      out.write("			<th> Price</th>\n");
      out.write("			<th> quantity</th>\n");
      out.write("			</tr>\n");
      out.write("		");
 Set<Entry<Integer, CartItem>> entrySet = cart.entrySet();
		for(Entry<Integer, CartItem> entry : entrySet){
			
      out.write("\n");
      out.write("			<tr>\n");
      out.write("				<td>");
      out.print( entry.getValue().getItemId());
      out.write(" </td>\n");
      out.write("				<td>");
      out.print( entry.getValue().getRestId());
      out.write(" </td>\n");
      out.write("				<td>");
      out.print( entry.getValue().getName());
      out.write(" </td>\n");
      out.write("				<td>");
      out.print( entry.getValue().getPrice() );
      out.write("</td>\n");
      out.write("				<td>");
      out.print( entry.getValue().getQuantity() );
      out.write("</td>\n");
      out.write("			</tr>\n");
      out.write("		");
 } 
      out.write("\n");
      out.write("		<tr>\n");
      out.write("			<td colspan=\"3\" id=\"totle1\"><b>Total Price</b></td>\n");
      out.write("			<td colspan=\"2\" id=\"totle2\"><b>");
      out.print( totalPrice );
      out.write("</b></td>\n");
      out.write("		</tr>\n");
      out.write("		</table>\n");
      out.write("   ");
}
	
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("<!-- <h1  style=\"text-align:center; font-size: 50px; font-weight: bold; animation: highlight3 2s infinite alternate; text-shadow: 2px 2px 4px #888;\"> See the View Cart Items</h1> -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
